name: Build, Lint, Test and possibly release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ "published" ]
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: read

jobs:
  build-lint-test-release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Install Node 20
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Check for vulnerabilities
        run: npm audit

      - name: Run Linter
        run: npm run lint

      - name: Build Code
        run: npm run compile

      - name: Test server
        working-directory: server
        run: npm run test

      - name: Publish
        if: success() && startsWith(github.ref, 'refs/tags/')
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          OVSX_PAT: ${{ secrets.OVSX_PAT }}

