name: Build, Lint and Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build-lint-test:
    name: Node
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Install Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Build Code
        run: npm run compile

      - name: Test server
        working-directory: server
        run: npm run test

      # deactive as does not work on CI
      # - name: Run Unit Tests
      #   run: xvfb-run -a npm run test
